### ISSUE TITLE
DNS leakage in VPN mode

### ISSUE THREAD

**Issue by mollaahmadi** [n8fr8/orbot#19]
DNS requests are leaked in VPN mode on marshmallow.

**Comment by mollaahmadi** [comment]
I think I found the root reason of this bug.
Since Android 4.4, DNS queries are handled using the *netd* and on the new Android, netd traffic bypasses the software VPN of Orbot. However, the netd can be configured to use the Tor local DNS server using *ndc* program.
This is described at [this stackexchange page](http://android.stackexchange.com/questions/62081/how-to-change-mobile-connectionss-dns-on-android-kitkat).

**Comment by n8fr8** [comment]
Thanks for the find! There are some other behavior changes in Android 6 as well we are investigating. We'll have an update out very soon.

BTW, what device are you on?

**Comment by n8fr8** [comment]
This is now fixed in the latest Orbot v15.1.0 Alpha releases. Please test and confirm!

APK: https://guardianproject.info/releases/Orbot-v15.1.0-ALPHA-3.apk
ASC: https://guardianproject.info/releases/Orbot-v15.1.0-ALPHA-3.apk.asc

More her: https://lists.mayfirst.org/pipermail/guardian-dev/2016-January/004586.html

**Comment by andreyde** [comment]
Seems to be still broken.
DNS traf goes to 8.8.8.8 via wlan0 iface

Orbot 15.1.2
Cyanogenmod 12.1
